import numpy as np
print("Jerry James")
uninit_array=np.empty(shape=(2,3))
print("Un initialized array")
print(uninit_array)
one=np.ones(shape=(2,3))
print("Araay with ones")
print(one)
zero=np.zeros(shape=(2,3))
print("array with zeros")
print(zero)