import numpy as np
matrix1=np.array([ [1,2,3],[4,5,6],[7,8,9] ])
matrix2=np.array([ [10,11,12],[13,14,15],[14,15,16] ])
print(f"Sum of matrix:\n{matrix1 + matrix2}")
print(f"Subtraction of 2 matrix\n{matrix2 - matrix1}")
print(f"Individual matrix multiplication\n{matrix1 * matrix2}")
print(f"Matrix division\n{matrix1 / matrix2}")
print(f"Matrix multiplication\n{np.dot(matrix1,matrix2)}")
print(f"Transpose of matrix 1\n{np.transpose(matrix1)}")
print(f"Sum of diagonal elements of matrix 1\n{np.trace(matrix1)}")